# Generated by Django 3.2.12 on 2023-06-01 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230601_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people_you_may_know',
            field=models.ManyToManyField(related_name='_account_user_people_you_may_know_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
