# Generated by Django 3.2.12 on 2023-06-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_people_you_may_know'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
