# Generated by Django 3.2.12 on 2023-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20230601_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postattachment',
            options={'verbose_name': 'Фото Поста', 'verbose_name_plural': 'Фото Постов'},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={'verbose_name': 'Популярное', 'verbose_name_plural': 'Популярные'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватное'),
        ),
    ]
